Lab4ED1/Lab4ED1/Models/Listado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab4ED1.Models
{
    public class Listado
    {
        List<T> faltantes = new List<T>();
        List<T> coleccionadas = new List<T>();
        List<T> cambios = new List<T>();
    }
}

Lab4ED1/Lab4ED1/Controllers/CargaCalcomaniaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net;
using Lab4ED1.DB;
using Lab4ED1.Models;

namespace Lab4ED1.Controllers
{
    public class CargaCalcomaniaController : Controller
    {
        JsonConnection db = JsonConnection.getInstance;

        // GET: CargaCalcomania
        public ActionResult Index()
        {
            return View(db.listaCalcomaniasCargadas);
        }
        public ActionResult Cambio()
        {
            return View(db.listaCalcomaniaCambios);
        }
        public ActionResult Buscar1()
        {
            return View(db.listaCalcomaniaColeccionada.ToList());
        }
       
        
        public ActionResult Listado()
        {
            return View(db.listaCalcomaniaFaltantes.ToList());
        }

        public ActionResult Buscar(int id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Calcomania cg = db.listaCalcomaniaColeccionada.Find(x => x.numero == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }
      

        // GET: CargaPartido/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CargaPartido/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Create1()
        {
            return View();
        }


        // POST: CargaPartido/Create
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase postedFile)
        {

           



            if (postedFile != null)
            {


                string filepath = string.Empty;

                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                filepath = path + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);
                postedFile.SaveAs(filepath);

                string csvData = System.IO.File.ReadAllText(filepath);

               
                db.listaCalcomaniasCargadas.Clear();
                Lista<Calcomania> listado = new Lista<Calcomania>();
                try
                {
                    JObject json = JObject.Parse(csvData);
                    
                    foreach (JProperty property in json.Properties())
                    {
                        
                        string x = property.Value.ToString();
                        Lista<int> y = JsonConvert.DeserializeObject<Lista<int>>(x);
                        db.DiccionarioListados.Add(y.nombre, y);
                    }
                    for (int i = 0; i < db.DiccionarioListados.Values.Count; i++)
                    {

                        for (int j = 0; j < db.DiccionarioListados.Values.ElementAt(i).coleccionadas.Count; j++)
                        {
                            Calcomania nuevaCalcomania = new Calcomania();
                            nuevaCalcomania.nombre = db.DiccionarioListados.Values.ElementAt(i).nombre;
                            nuevaCalcomania.numero = db.DiccionarioListados.Values.ElementAt(i).coleccionadas.ElementAt(j);
                            db.listaCalcomaniaColeccionada.Add(nuevaCalcomania);
                            db.listaCalcomaniasCargadas.Add(nuevaCalcomania);
                        }
                        for (int j = 0; j < db.DiccionarioListados.Values.ElementAt(i).cambios.Count; j++)
                        {
                            Calcomania nuevaCalcomania = new Calcomania();
                            nuevaCalcomania.nombre = db.DiccionarioListados.Values.ElementAt(i).nombre;
                            nuevaCalcomania.numero = db.DiccionarioListados.Values.ElementAt(i).cambios.ElementAt(j);
                            db.listaCalcomaniaCambios.Add(nuevaCalcomania);
                            db.listaCalcomaniasCargadas.Add(nuevaCalcomania);
                        }
                        for (int j = 0; j < db.DiccionarioListados.Values.ElementAt(i).faltantes.Count; j++)
                        {
                            Calcomania nuevaCalcomania = new Calcomania();
                            nuevaCalcomania.nombre = db.DiccionarioListados.Values.ElementAt(i).nombre;
                            nuevaCalcomania.numero = db.DiccionarioListados.Values.ElementAt(i).faltantes.ElementAt(j);
                            nuevaCalcomania.falta = true;
                            db.listaCalcomaniaFaltantes.Add(nuevaCalcomania);
                            db.listaCalcomaniasCargadas.Add(nuevaCalcomania);
                        }
                    }


                    foreach (Calcomania item in db.listaCalcomaniasCargadas)
                    {
                        db.DiccionarioFaltantes.Add(item, item.falta);
                    }

                    ViewBag.Message = "Cargado Exitosamente";


                }
                catch (Exception)
                {
                    ViewBag.Message = "Dato erroneo.";
                }

            }

            return View();
        }
        [HttpPost]
        public ActionResult Create1(HttpPostedFileBase postedFile)
        {





            if (postedFile != null)
            {


                string filepath = string.Empty;

                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                filepath = path + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);
                postedFile.SaveAs(filepath);

                string csvData = System.IO.File.ReadAllText(filepath);

                
                db.listaCalcomaniasCargadas.Clear();
               
                try
                {
                    JObject json = JObject.Parse(csvData);

                    foreach (JProperty property in json.Properties())
                    {
                        Lista<int> listado = new Lista<int>();
                        string x = property.Value.ToString();
                        Calcomania y = JsonConvert.DeserializeObject<Calcomania>(x);

                        db.DiccionarioFaltantes.Add(y, y.falta);
                        db.listaCalcomaniasCargadas.Add(y);
                        if (y.falta == true)
                        {
                            listado.faltantes.Add(y.numero);
                            db.listaCalcomaniaFaltantes.Add(y);
                        }
                        else
                        {
                            
                            if (listado.coleccionadas.Contains(y.numero))
                            {
                                listado.cambios.Add(y.numero);
                                db.listaCalcomaniaCambios.Add(y);
                            }
                            else
                            {
                                listado.coleccionadas.Add(y.numero);
                                db.listaCalcomaniaColeccionada.Add(y);
                            }
                            
                        }
                        db.DiccionarioListados.Add(y.nombre, listado);
                    }
                    
                  

                    ViewBag.Message = "Cargado Exitosamente";


                }
                catch (Exception)
                {
                    ViewBag.Message = "Dato erroneo.";
                }

            }

            return View();
        }
       

        
        // GET: CargaPartido/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Calcomania cl = db.listaCalcomaniasCargadas.FirstOrDefault(x => x.numero == id);

            if (cl == null)
            {
                return HttpNotFound();
            }

            return View(cl);
        }

        // POST: CargaPartido/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "numero,nombre,falta")] Calcomania cl)
        {
            try
            {
                // TODO: Add update logic here

                Calcomania clBuscada = db.listaCalcomaniasCargadas.FirstOrDefault(x => x.numero == cl.numero);
                if (clBuscada == null)
                {
                    return HttpNotFound();
                }
                clBuscada.nombre = cl.nombre;
                clBuscada.numero = cl.numero;
                clBuscada.falta = cl.falta;
             

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CargaPartido/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Calcomania cg = db.listaCalcomaniasCargadas.Find(x => x.numero == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }

        // POST: CargaPartido/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                if (id == null)
                {

Lab4ED1/Lab4ED1/Views/CargaCalcomania/Buscar.cshtml
@model Lab4ED1.Models.Calcomania

@{
    ViewBag.Title = "Buscar";
}

<<h2>Buscar Sticker del album de la Copa Mundial de la FIFA Rusia 2018</h2>
<div>
    <h4>Calcomania</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>
    </dl>
    <br />
    @Html.ActionLink("Volver a la lista", "Lista")

Lab4ED1/Lab4ED1/Views/CargaCalcomania/Buscar1.cshtml
@using Lab4ED1.Models;
@model IEnumerable<Lab4ED1.Models.Calcomania>

@{
    ViewBag.Title = "Buscar1";
}
<head>
    <meta charset="UTF-8" />
    <title>Sticker World  Cup</title>
    <link rel="stylesheet" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.Overlay/Css/jquery.tosrus.all.css" />
    <link rel="stylesheet" type="text/css" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Css/Core.css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js" async></script>
    <script type="text/javascript">dataLayer = [];</script>
    <script type="text/javascript">(function (w, d, s, l, i) {w[l] = w[l] || [];w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';j.async = true;j.src = '//www.googletagmanager.com/gtm.js?id=' + i + dl;f.parentNode.insertBefore(j, f);})(window, document, 'script', 'dataLayer', 'GTM-PXS29D');</script>
    <meta name="robots" content="index,follow" />
    <link rel="canonical" href="https://2018fifaworldcuprussia.paninigroup.com/es_ve" />

    <link rel="alternate" hreflang="es" href="https://2018fifaworldcuprussia.paninigroup.com/es_ve" />
    <link rel="icon" type="image/x-icon; charset=binary" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Icons/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon; charset=binary" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Icons/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="X-UA-Compatible" content="IE=edge" />
    <meta name="google-site-verification" content="google107b554615034cb3" />
    <meta name="msvalidate.01" content="CC011F120D8BF62F4385F67B817D1BB4" />
</head>
<h2>Buscar por tipo Sticker del album de la Copa Mundial de la FIFA Rusia 2018</h2>
<div>
    <h4>Sticker</h4>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.falta)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.falta)
                </td>
            </tr>
        }
    </table>
    <br />
    @Html.ActionLink("Volver a la lista", "Lista")

    <footer>
</div><div class="innerArea">
    <div class="copy-legals copy-panini">
        <div class="logo-footer-group"><img src="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Images/logo_panini%402x.png" alt="Panini S.p.A. - www.paninigroup.com" class="logo-footer logo-panini" /></div><div class="legals">
            <div id="pnn-footer"></div>
            <script type="text/javascript">var locale = 'en-gb';var format = 'html';var type = 'pnnns';</script>
            <script src="https://legals.paninicloud.com/legals.inject.js"></script>
        </div>
    </div><div class="copy-legals copy-fifa"><p>© FIFA, FIFA’s Official Licensed Product Logos, and the Emblems, Mascots, Posters and Trophies of the FIFA World Cup™ tournaments are copyrights and/or trademarks of FIFA.</p></div>
</div>
</footer>

Lab4ED1/Lab4ED1/Views/CargaCalcomania/Create.cshtml
@model Lab4ED1.Models.Calcomania

@{
    ViewBag.Title = "Create";
}

<head>
    <meta charset="UTF-8" />
    <title>La Colección - Sticker World  Cup</title>
    <link rel="stylesheet" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.Overlay/Css/jquery.tosrus.all.css" />
    <link rel="stylesheet" type="text/css" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Css/Core.css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js" async></script>
    <script type="text/javascript">dataLayer = [];</script>
    <script type="text/javascript">(function (w, d, s, l, i) {w[l] = w[l] || [];w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';j.async = true;j.src = '//www.googletagmanager.com/gtm.js?id=' + i + dl;f.parentNode.insertBefore(j, f);})(window, document, 'script', 'dataLayer', 'GTM-PXS29D');</script>
    <meta name="robots" content="index,follow" />
    <link rel="canonical" href="https://2018fifaworldcuprussia.paninigroup.com/es_ve/the-collection" />


    <link rel="alternate" hreflang="es" href="https://2018fifaworldcuprussia.paninigroup.com/es_ve/the-collection" />
    <link rel="icon" type="image/x-icon; charset=binary" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Icons/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon; charset=binary" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Icons/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="X-UA-Compatible" content="IE=edge" />
    <meta name="google-site-verification" content="google107b554615034cb3" />
    <meta name="msvalidate.01" content="CC011F120D8BF62F4385F67B817D1BB4" />
</head>
<body class="core" id="page-the-collection">

    
    <main>
        <div class="page-title with-background" style="background-image:url(&quot;https://2018fifaworldcuprussia.paninigroup.com/_Resources/Persistent/d301a014163c4e8cabcc40f61b72863e32f8d006/2018fwc_BgTop_Collection_INT-2560x506.jpg&quot;)"><h1>La Colección</h1></div>
        <div class="wrapper">
            <div class="contents neos-contentcollection">
                <div class="neos-nodetypes-headline">
                    <div>
                        <h3>Colección Oficial de Stickers con licencia de la Copa Mundial de la FIFA Rusia 2018™</h3>
                    </div>
                </div>
                <h2>Carga de Archivo Json de album para Listado de tu Colección Oficial de stickers de la COPA MUNDIAL FIFA™</h2>
                @using (Html.BeginForm("Create", "CargaCalcomania", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <span>Seleccionar archivo:</span>
                    <input type="file" name="postedFile" />
                    <br />
                    <input type="submit" value="Subir" />
                    <span style="color:green">@ViewBag.Message</span><br />
                }
                <br />
                <br />
                <br />
                <div>
                    @Html.ActionLink("Mostrar Stikers faltantes", "Listado")<br />
                   
                </div>
                <div class="neos-nodetypes-headline">
                    <div>
                        <h5>¡LA TENGO, LA TENGO, ME FALTA! Experimenta la emoción del fútbol con la nueva Colección Oficial de Stickers con licencia de la Copa Mundial de la FIFA Rusia 2018™!</h5>
                    </div>
                </div>
                <div class="neos-nodetypes-text">
                    <div>
                        <p>Cada cuatro años, el fútbol se convierte en el centro de atención ya que 32 naciones compiten por la más grande recompensa deportiva: la COPA MUNDIAL FIFA ™. ¡Este año está más emocionantes que nunca ya que la elite futbolística mundial se dirige a Rusia con la esperanza de que sean ellos los que consigan el trofeo!</p>

                        <p>Panini se enorgullece en ofrecerte la única Colección oficial de stickers&nbsp;de la Copa Mundial de la FIFA Rusia 2018™ para este célebre evento. Esta impresionante colección presenta a los 32 equipos presentados con gráficas llamativas e increíbles imágenes de las superestrellas del fútbol más famosas del mundo.</p>

                        <p>
                            Hay 670 stickers para coleccionar, incluidos los 50 stickers especiales. ¡Los coleccionistas pueden comenzar su colección con un paquete inicial que incluye el álbum y 5 sobres!<br />
                            &nbsp;
                        </p>
                    </div>
                </div>
                <div class="neos-nodetypes-headline">
                    <div>
                        <h4>¡YA A LA VENTA! ¡La Colección Oficial de Stickers de la Copa Mundial de la FIFA Rusia 2018™ de Panini! ¡Déjate atrapar! #LaTengoNoLaTengo&nbsp;</h4>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <footer>

        </div><div class="innerArea">
            <div class="copy-legals copy-panini">
                <div class="logo-footer-group"><img src="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Images/logo_panini%402x.png" alt="Panini S.p.A. - www.paninigroup.com" class="logo-footer logo-panini" /></div><div class="legals">
                    <div id="pnn-footer"></div>
                    <script type="text/javascript">var locale = 'en-gb';var format = 'html';var type = 'pnnns';</script>
                    <script src="https://legals.paninicloud.com/legals.inject.js"></script>
                </div>
            </div><div class="copy-legals copy-fifa"><p>© FIFA, FIFA’s Official Licensed Product Logos, and the Emblems, Mascots, Posters and Trophies of the FIFA World Cup™ tournaments are copyrights and/or trademarks of FIFA.</p></div>
        </div>
    </footer>

   
</body></html>

Lab4ED1/Lab4ED1/Views/CargaCalcomania/Create1.cshtml
@model Lab4ED1.Models.Calcomania

@{
    ViewBag.Title = "Create";
}

<head>
    <meta charset="UTF-8" />
    <title>La Colección - Sticker World  Cup</title>
    <link rel="stylesheet" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.Overlay/Css/jquery.tosrus.all.css" />
    <link rel="stylesheet" type="text/css" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Css/Core.css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js" async></script>
    <script type="text/javascript">dataLayer = [];</script>
    <script type="text/javascript">(function (w, d, s, l, i) {w[l] = w[l] || [];w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';j.async = true;j.src = '//www.googletagmanager.com/gtm.js?id=' + i + dl;f.parentNode.insertBefore(j, f);})(window, document, 'script', 'dataLayer', 'GTM-PXS29D');</script>
    <meta name="robots" content="index,follow" />
    <link rel="canonical" href="https://2018fifaworldcuprussia.paninigroup.com/es_ve/the-collection" />


    <link rel="alternate" hreflang="es" href="https://2018fifaworldcuprussia.paninigroup.com/es_ve/the-collection" />
    <link rel="icon" type="image/x-icon; charset=binary" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Icons/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon; charset=binary" href="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Icons/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="X-UA-Compatible" content="IE=edge" />
    <meta name="google-site-verification" content="google107b554615034cb3" />
    <meta name="msvalidate.01" content="CC011F120D8BF62F4385F67B817D1BB4" />
</head>
<body class="core" id="page-the-collection">

    
    <main>
        <div class="page-title with-background" style="background-image:url(&quot;https://2018fifaworldcuprussia.paninigroup.com/_Resources/Persistent/d301a014163c4e8cabcc40f61b72863e32f8d006/2018fwc_BgTop_Collection_INT-2560x506.jpg&quot;)"><h1>La Colección</h1></div>
        <div class="wrapper">
            <div class="contents neos-contentcollection">
                <div class="neos-nodetypes-headline">
                    <div>
                        <h3>Colección Oficial de Stickers con licencia de la Copa Mundial de la FIFA Rusia 2018™</h3>
                    </div>
                </div>
                <h2>Carga de Archivo Json de estampas para Listado de tu Colección Oficial de stickers de la COPA MUNDIAL FIFA™</h2>
                @using (Html.BeginForm("Create1", "CargaCalcomania", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <span>Seleccionar archivo:</span>
                    <input type="file" name="postedFile" />
                    <br />
                    <input type="submit" value="Subir" />
                    <span style="color:green">@ViewBag.Message</span><br />
                }
                <br />
                <br />
                <br />
                <div>
                    @Html.ActionLink("Mostrar Stikers faltantes", "Buscar")<br />
                   
                </div>
                <div class="neos-nodetypes-headline">
                    <div>
                        <h5>¡LA TENGO, LA TENGO, ME FALTA! Experimenta la emoción del fútbol con la nueva Colección Oficial de Stickers con licencia de la Copa Mundial de la FIFA Rusia 2018™!</h5>
                    </div>
                </div>
                <div class="neos-nodetypes-text">
                    <div>
                        <p>Cada cuatro años, el fútbol se convierte en el centro de atención ya que 32 naciones compiten por la más grande recompensa deportiva: la COPA MUNDIAL FIFA ™. ¡Este año está más emocionantes que nunca ya que la elite futbolística mundial se dirige a Rusia con la esperanza de que sean ellos los que consigan el trofeo!</p>

                        <p>Panini se enorgullece en ofrecerte la única Colección oficial de stickers&nbsp;de la Copa Mundial de la FIFA Rusia 2018™ para este célebre evento. Esta impresionante colección presenta a los 32 equipos presentados con gráficas llamativas e increíbles imágenes de las superestrellas del fútbol más famosas del mundo.</p>

                        <p>
                            Hay 670 stickers para coleccionar, incluidos los 50 stickers especiales. ¡Los coleccionistas pueden comenzar su colección con un paquete inicial que incluye el álbum y 5 sobres!<br />
                            &nbsp;
                        </p>
                    </div>
                </div>
                <div class="neos-nodetypes-headline">
                    <div>
                        <h4>¡YA A LA VENTA! ¡La Colección Oficial de Stickers de la Copa Mundial de la FIFA Rusia 2018™ de Panini! ¡Déjate atrapar! #LaTengoNoLaTengo&nbsp;</h4>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <footer>

        </div><div class="innerArea">
            <div class="copy-legals copy-panini">
                <div class="logo-footer-group"><img src="https://2018fifaworldcuprussia.paninigroup.com/_Resources/Static/Packages/Panini.StickerWorldCup/Images/logo_panini%402x.png" alt="Panini S.p.A. - www.paninigroup.com" class="logo-footer logo-panini" /></div><div class="legals">
                    <div id="pnn-footer"></div>
                    <script type="text/javascript">var locale = 'en-gb';var format = 'html';var type = 'pnnns';</script>
                    <script src="https://legals.paninicloud.com/legals.inject.js"></script>
                </div>
            </div><div class="copy-legals copy-fifa"><p>© FIFA, FIFA’s Official Licensed Product Logos, and the Emblems, Mascots, Posters and Trophies of the FIFA World Cup™ tournaments are copyrights and/or trademarks of FIFA.</p></div>
        </div>
    </footer>

   
</body></html>

Lab4ED1/Lab4ED1/Views/CargaCalcomania/Delete.cshtml
@model Lab4ED1.Models.Calcomania

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>¿Está seguro de borrar ésto?</h3>
<div>
    <h4>Calcomania</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.falta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.falta)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lab4ED1/Lab4ED1/Views/CargaCalcomania/Details.cshtml
@model Lab4ED1.Models.Calcomania

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Calcomania</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.falta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.falta)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.numero  }) |
    @Html.ActionLink("Back to List", "Index")
</p>